transform_type: 'lifting'
transform_name: "DiscreteConfigurationComplexLifting"
k: 2
feature_aggregation: "sum"
feature_lifting: ProjectionSum

# Required for all liftings to make the pipeline executable
complex_dim: 3
preserve_edge_attr: False
neighborhoods: ${oc.select:model.backbone.neighborhoods,${oc.select:model.preprocessing_params.neighborhoods,null}}
