defaults:
  - data_manipulations: identity # PROTEINS dataset needs identity transform to avoid adding random float feature to feature matrix
  - data_manipulations@CombinedPSEs: combined_positional_and_structural_encodings
  - liftings@_here_: ${get_required_lifting:${dataset},${model}}
