default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: fix-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: check-symlinks
      - id: mixed-line-ending
        args:
          - --fix=no
      - id: check-added-large-files
        args:
          - --maxkb=2048
      - id: requirements-txt-fixer

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.9
    hooks:
      - id: ruff-format
      - id: ruff

  - repo: https://github.com/numpy/numpydoc
    rev: v1.8.0
    hooks:
      - id: numpydoc-validation
        exclude: ^(test/|tutorials/|notebooks/|scripts/|docs/|2026_tdl_challenge/)
