# GIN cell
python -m topobench model=graph/gin dataset=graph/NCI1 optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 trainer.devices=\[2\] callbacks.early_stopping.patience=10 logger.wandb.project=HOPSE_rebuttal logger.wandb.tags=["gin","graph","cell","no_pse"] --multirun
python -m topobench model=graph/gin dataset=graph/NCI109 optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 trainer.devices=\[2\] callbacks.early_stopping.patience=10 logger.wandb.project=HOPSE_rebuttal logger.wandb.tags=["gin","graph","cell","no_pse"] --multirun
python -m topobench model=graph/gin dataset=graph/PROTEINS optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.num_layers=1 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 trainer.devices=\[2\] callbacks.early_stopping.patience=10 logger.wandb.project=HOPSE_rebuttal logger.wandb.tags=["gin","graph","cell","no_pse"] --multirun
python -m topobench model=graph/gin dataset=graph/MUTAG optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=64 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=64 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 trainer.devices=\[2\] callbacks.early_stopping.patience=10 logger.wandb.project=HOPSE_rebuttal logger.wandb.tags=["gin","graph","cell","no_pse"] --multirun
python -m topobench model=graph/gin dataset=graph/ZINC optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=32 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 callbacks.early_stopping.min_delta=0.005 transforms.one_hot_node_degree_features.degrees_field=x seed=42,3,5,23,150 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 trainer.devices=\[2\] callbacks.early_stopping.patience=10 logger.wandb.project=HOPSE_rebuttal logger.wandb.tags=["gin","graph","cell","no_pse"] --multirun

# GIN simplicial
python -m topobench model=graph/gin dataset=graph/NCI1 optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 trainer.devices=\[2\] callbacks.early_stopping.patience=10 logger.wandb.project=HOPSE_rebuttal logger.wandb.tags=["gin","graph","simplicial","no_pse"] --multirun
python -m topobench model=graph/gin dataset=graph/NCI109 optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=128 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 trainer.devices=\[2\] callbacks.early_stopping.patience=10 logger.wandb.project=HOPSE_rebuttal logger.wandb.tags=["gin","graph","simplicial","no_pse"] --multirun
python -m topobench model=graph/gin dataset=graph/PROTEINS optimizer.parameters.lr=0.01 model.feature_encoder.out_channels=64 model.backbone.num_layers=1 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=128 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 trainer.devices=\[2\] callbacks.early_stopping.patience=10 logger.wandb.project=HOPSE_rebuttal logger.wandb.tags=["gin","graph","simplicial","no_pse"] --multirun
python -m topobench model=graph/gin dataset=graph/MUTAG optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=64 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.5 dataset.dataloader_params.batch_size=64 dataset.split_params.data_seed=0,3,5,7,9 trainer.max_epochs=500 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 trainer.devices=\[2\] callbacks.early_stopping.patience=10 logger.wandb.project=HOPSE_rebuttal logger.wandb.tags=["gin","graph","simplicial","no_pse"] --multirun
python -m topobench model=graph/gin dataset=graph/ZINC optimizer.parameters.lr=0.001 model.feature_encoder.out_channels=32 model.backbone.num_layers=4 model.feature_encoder.proj_dropout=0.25 dataset.dataloader_params.batch_size=128 callbacks.early_stopping.min_delta=0.005 transforms.one_hot_node_degree_features.degrees_field=x seed=42,3,5,23,150 trainer.max_epochs=1000 trainer.min_epochs=50 trainer.check_val_every_n_epoch=5 trainer.devices=\[2\] callbacks.early_stopping.patience=10 logger.wandb.project=HOPSE_rebuttal logger.wandb.tags=["gin","graph","simplicial","no_pse"] --multirun
