loader:
  _target_: topobench.data.loaders.MantraSimplicialDatasetLoader
  parameters:
    data_domain: simplicial
    data_type: topological
    data_name: MANTRA_orientation
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}
    manifold_dim: 2
    version: "v0.0.5"
    load_as_graph: False
    task_variable: "orientable" # Options: ['name', 'genus', 'orientable'] To use 'torsion_coefficients', 'betti_numbers' fix multilabel multiclass issue
    model_domain: ${model.model_domain}
    neighborhoods: ${oc.select:model.backbone.neighborhoods,${oc.select:model.preprocessing_params.neighborhoods,null}}
    signed: True
    slice: False

# Data definition
parameters:
  # In the case of higher-order datasets we have multiple feature dimentions
  num_features: [1,1,1] # [1,1,1]
  num_classes: 2 # Num classes depents on the task_variable

  # Dataset parameters
  task: classification
  loss_type: cross_entropy
  monitor_metric: f1
  task_level: graph
  data_seed: 0
  metrics: [accuracy, precision, recall, auroc, f1] # Available options: accuracy, auroc, precision, recall, f1

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: stratified #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation
  train_prop: 0.5 # for "random" strategy splitting

# Dataloader parameters
dataloader_params:
  batch_size: 256
  num_workers: 0
  pin_memory: False
