
loader:
  _target_: topobench.data.loaders.OGBGDatasetLoader
  parameters:
    data_domain: graph
    data_type: OGBGDataset
    data_name: ogbg-molhiv
    data_dir: ${paths.data_dir}/${dataset.loader.parameters.data_domain}/${dataset.loader.parameters.data_type}

# Dataset parameters
parameters:
  num_features:
  - 9 # Node features
  - 3 # Edge features
  num_classes: 2
  task: classification
  loss_type: cross_entropy
  monitor_metric: auroc
  task_level: graph
  preserve_edge_attr_if_lifted: True

#splits
split_params:
  learning_setting: inductive
  data_split_dir: ${paths.data_dir}/data_splits/${dataset.loader.parameters.data_name}
  data_seed: 0
  split_type: "fixed" #'k-fold' # either "k-fold" or "random" strategies
  k: 10 # for "k-fold" Cross-Validation

# Dataloader parameters
dataloader_params:
  batch_size: 64
  num_workers: 0
  pin_memory: False
