_target_: topobench.model.TBModel

model_name: hopse_m
model_domain: cell

preprocessing_params:
  neighborhoods:
    - 'up_adjacency-0'
    # - 'up_adjacency-1'
    # - 'down_adjacency-1'
    # - 'down_adjacency-2'
    # - 'up_incidence-0'
    # - 'up_incidence-1'
    - 'down_incidence-1'
    - 'down_incidence-2'
  encodings: ["LapPE", "RWSE", "ElectrostaticPE", "HKdiagSE"]
  copy_initial: True

feature_encoder:
  _target_: topobench.nn.encoders.${model.feature_encoder.encoder_name}
  encoder_name: HOPSEFeatureEncoder
  dataset_in_channels: ${infer_in_channels:${dataset},${oc.select:transforms,null}}
  in_channels: ${transforms.hopse_encoding.in_channels}
  max_hop: ${transforms.hopse_encoding.max_hop}
  out_channels: 64
  proj_dropout: 0.0
  selected_dimensions:
    - 0
    - 1
    - 2
  all_ones: true
  use_bond_encoder: False
  use_atom_encoder: False

backbone:
  _target_: topobench.nn.backbones.combinatorial.HOPSE
  in_channels: ${model.backbone.hidden_channels}
  n_layers: 2
  max_hop: ${transforms.hopse_encoding.max_hop}
  hidden_channels: ${model.feature_encoder.out_channels}
  update_func: "leaky_relu"

backbone_wrapper:
  _target_: topobench.nn.wrappers.HOPSEWrapper
  _partial_: true
  wrapper_name: HOPSEWrapper
  out_channels: ${model.feature_encoder.out_channels}
  complex_dim: ${transforms.hopse_encoding.max_rank}
  max_hop: ${transforms.hopse_encoding.max_hop}
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}}

readout:
  _target_: topobench.nn.readouts.${model.readout.readout_name}
  readout_name: HOPSEReadout  #  Use <NoReadOut> in case readout is not needed Options: PropagateSignalDown
  max_hop: ${transforms.hopse_encoding.max_hop}
  num_cell_dimensions: ${infer_num_cell_dimensions:${oc.select:model.feature_encoder.selected_dimensions,null},${model.feature_encoder.in_channels}} # The highest order of cell dimensions to consider
  hidden_dim: ${model.feature_encoder.out_channels}
  out_channels: ${dataset.parameters.num_classes}
  task_level: ${dataset.parameters.task_level}
  pooling_type: sum
  complex_dim: ${transforms.hopse_encoding.max_rank}

# compile model for faster training with pytorch 2.0
compile: false
